- name: "Add to ksh interactive config: {{ description }}"
  ansible.builtin.include_tasks: add_config_lines.yml
  vars:
    shell_type: "ksh interactive"
    filepath: "{{ full_ksh_specific_dir_path }}/{{ interactive_filename }}"
    block_lines: "{{ config_lines }}"
    shell_specific_validate_cmd: "{{ validate_ksh }}"

