- name: "Add lines to {{ shell_type }} config: {{ description }}"
  ansible.builtin.blockinfile:
    path: "{{ filepath }}"
    insertafter: EOF
    block: "{{ block_lines }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ description }}"
    create: no
    state: present
    validate: "{{ shell_specific_validate_cmd }}"
  become: true
  become_user: root

