- name: "Replace .profile: make it source only core common files"
  ansible.builtin.include_tasks: replace_core_file.yml
  vars:
    filepath: "{{ home_dir }}/.profile"
    file_template: 'profile.j2'

