- name: "Replace .bash_profile: make it source only core common files"
  ansible.builtin.include_tasks: replace_core_file.yml
  vars:
    filepath: "{{ home_dir }}/.bash_profile"
    file_template: 'bash_profile.j2'
    validate: "{{ validate_sh }}"

- name: "Replace .bashrc: make it source only core common files"
  ansible.builtin.include_tasks: replace_core_file.yml
  vars:
    filepath: "{{ home_dir }}/.bashrc"
    file_template: 'bashrc.j2'
    validate: "{{ validate_sh }}"

- name: "Replace .bash_logout: make it source only core common files"
  ansible.builtin.include_tasks: replace_core_file.yml
  vars:
    filepath: "{{ home_dir }}/.bash_logout"
    file_template: 'bash_logout.j2'
    validate: "{{ validate_sh }}"

