- name: "Configure bash login config file '{{ cfg_shell_bash_login_file_path }}'"
  ansible.builtin.template:
    dest: "{{ cfg_shell_bash_login_file_path }}"
    src: "bash_profile.j2"
    mode: '644'
    force: true
    validate: "sh -n %s"
  become: true
  become_user: "{{ cfg_shell_user_name }}"

- name: "Configure bourne and ksh login config file '{{ cfg_shell_sh_ksh_login_file_path }}'"
  ansible.builtin.template:
    dest: "{{ cfg_shell_sh_ksh_login_file_path }}"
    src: "profile.j2"
    mode: '644'
    force: true
    validate: "sh -n %s"
  become: true
  become_user: "{{ cfg_shell_user_name }}"

- name: "Configure csh and tcsh login config file '{{ cfg_shell_csh_tcsh_login_file_path }}'"
  ansible.builtin.template:
    dest: "{{ cfg_shell_csh_tcsh_login_file_path }}"
    src: "login.j2"
    mode: '644'
    force: true
  become: true
  become_user: "{{ cfg_shell_user_name }}"

- name: "Configure zsh login config file '{{ cfg_shell_zsh_login_file_path }}'"
  ansible.builtin.template:
    dest: "{{ cfg_shell_zsh_login_file_path }}"
    src: "zprofile.j2"
    mode: '644'
    force: true
    validate: "sh -n %s"
  become: true
  become_user: "{{ cfg_shell_user_name }}"

